### ISSUE TITLE
The data.tar.gz file is corrupted

### ISSUE THREAD

**Issue by nsankethreddy** [datarootsio/face-mask-detection#24]
I was trying to execute your program. So I had to unzip the compressed data file but when i tried to uncompress it it gave the following error

Extracting through terminal
![Screenshot from 2020-10-05 21-44-32](https://user-images.githubusercontent.com/47980147/95105259-854d1200-0754-11eb-83a4-4aebe822d6ab.png)

Extraction through GUI
![Screenshot from 2020-10-05 21-55-54](https://user-images.githubusercontent.com/47980147/95106081-abbf7d00-0755-11eb-8795-aee52483a74d.png)

So i assume the data.tar.gz file is prolly corrupted.

If you could reupload a proper file, I'd be helpful :)
Or else you could also put up the data folder in google drive or a bucket and share the link.

**Comment by baturayo** [comment]
Thank you very much for your warning. The new data.tar.gz has been pushed with the new release. :)

**Comment by nsankethreddy** [comment]
Hey, the data.tar.gz is still corrupted 
![Screenshot from 2020-10-24 23-29-57](https://user-images.githubusercontent.com/47980147/97088925-c9477e80-1651-11eb-89c9-9e343272c678.png)
![Screenshot from 2020-10-24 23-30-31](https://user-images.githubusercontent.com/47980147/97088926-ca78ab80-1651-11eb-8f05-da6671b33f7b.png)

**Comment by baturayo** [comment]
Please make sure that [`git-lfs`](https://git-lfs.github.com/) is installed on your local. If you directly download the repo as a zip file then `data.tar.gz` cannot be extracted. After installing `git-lfs`, please clone the repo with `git clone https://github.com/datarootsio/face-mask-detection.git` command.
