### ISSUE TITLE
data.tar.gz dosyası hatalı

### ISSUE THREAD

**Issue by askinucuncu** [datarootsio/face-mask-detection#29]
Merhaba, data.tar.gz dosyası hatalı.

tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

!file data.tar.gz
data.tar.gz: ASCII text

Dosyayı yeniden yüklemeniz mümkün müdür?

**Comment by baturayo** [comment]
Please refer to this [issue](https://github.com/datarootsio/face-mask-detection/issues/24#issuecomment-716060335) for your problem. You need to install `git-lfs`. I hope it helps.
